apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: demo-argocd
  namespace: argocd
spec:
  template:
    metadata: { name: '{{name}}-{{environment}}' }
    spec:
      project: demo-argocd
      syncPolicy:
        automated: null
        syncOptions: [CreateNamespace=true]
      destination:
        namespace: '{{name}}-{{environment}}'
        server: https://kubernetes.default.svc
      source:
        path: '{{name}}/helm'
        targetRevision: main
        repoURL: https://github.com/MP281X/demo-argocd
        helm: { valueFiles: ['../{{environment}}.yaml'] }
  generators:
    - list:
        elements:
          - { name: app1, environment: dev }
          - { name: app1, environment: prod }
          - { name: app1, environment: staging }
