apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels: { app: {{ .Chart.Name }} }
spec:
  replicas: 3
  revisionHistoryLimit: 0
  selector: { matchLabels: { app: {{ .Chart.Name }} } }
  template:
    metadata: { labels: { app: {{ .Chart.Name }} } }
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          env:
            {{- range $key, $value := .Values.env }}
              - name: {{ $key }}
                value: {{ $value | quote }}
            {{- end }}
